## Statistics Assignment

In [1]:
import numpy as np
import pandas as pd

## Preliminary Data Analysis

In [2]:
possums =pd.read_csv("possum.csv")
possums.head()

,case,site,Pop,sex,age,hdlngth,skullw,totlngth,taill,footlgth,earconch,eye,chest,belly
0,1,1,Vic,m,8.0,94.1,60.4,89.0,36.0,74.5,54.5,15.2,28.0,36.0
1,2,1,Vic,f,6.0,92.5,57.6,91.5,36.5,72.5,51.2,16.0,28.5,33.0
2,3,1,Vic,f,6.0,94.0,60.0,95.5,39.0,75.4,51.9,15.5,30.0,34.0
3,4,1,Vic,f,6.0,93.2,57.1,92.0,38.0,76.1,52.2,15.2,28.0,34.0
4,5,1,Vic,f,2.0,91.5,56.3,85.5,36.0,71.0,53.2,15.1,28.5,33.0

In [3]:
possums.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 104 entries, 0 to 103
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   case      104 non-null    int64
 1   site      104 non-null    int64
 2   Pop       104 non-null    object
 3   sex       104 non-null    object
 4   age       102 non-null    float64
 5   hdlngth   104 non-null    float64
 6   skullw    104 non-null    float64
 7   totlngth  104 non-null    float64
 8   taill     104 non-null    float64
 9   footlgth  103 non-null    float64
 10  earconch  104 non-null    float64
 11  eye       104 non-null    float64
 12  chest     104 non-null    float64
 13  belly     104 non-null    float64
dtypes: float64(10), int64(2), object(2)
memory usage: 11.5+ KB

In [16]:
# Descriptive Statistic of the Data
print("Descriptive Statistics of Data")
possums.describe(include='all')

Descriptive Statistics of Data

,case,site,Pop,sex,age,hdlngth,skullw,totlngth,taill,footlgth,earconch,eye,chest,belly
count,104.000000,104.000000,104,104,102.000000,104.000000,104.000000,104.000000,104.000000,103.000000,104.000000,104.000000,104.000000,104.000000
unique,NaN,NaN,2,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,NaN,other,m,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,NaN,58,61,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,52.500000,3.625000,NaN,NaN,3.833333,92.602885,56.883654,87.088462,37.009615,68.459223,48.130769,15.046154,27.000000,32.586538
std,30.166206,2.349086,NaN,NaN,1.909244,3.573349,3.113426,4.310549,1.959518,4.395306,4.109380,1.050374,2.045597,2.761949
min,1.000000,1.000000,NaN,NaN,1.000000,82.500000,50.000000,75.000000,32.000000,60.300000,40.300000,12.800000,22.000000,25.000000
25%,26.750000,1.000000,NaN,NaN,2.250000,90.675000,54.975000,84.000000,35.875000,64.600000,44.800000,14.400000,25.500000,31.000000
50%,52.500000,3.000000,NaN,NaN,3.000000,92.800000,56.350000,88.000000,37.000000,68.000000,46.800000,14.900000,27.000000,32.500000
75%,78.250000,6.000000,NaN,NaN,5.000000,94.725000,58.100000,90.000000,38.000000,72.500000,52.000000,15.725000,28.000000,34.125000
max,104.000000,7.000000,NaN,NaN,9.000000,103.100000,68.600000,96.500000,43.000000,77.900000,56.200000,17.800000,32.000000,40.000000

In [ ]:
# Observations
'''
1. from the count row, it shows there are 104 possums used in the study except for age where column AGE and FOOTLGTH where 102 and 103 possums are observed respectively
2. SIte: the sight shows that the possums are trapped across 7sites
3. 
'''

In [5]:
possums1 = possums.copy()

In [6]:
# possums1.drop("Pop", axis = 1, inplace = True)
possums1.head(1)

,case,site,Pop,sex,age,hdlngth,skullw,totlngth,taill,footlgth,earconch,eye,chest,belly
0,1,1,Vic,m,8.0,94.1,60.4,89.0,36.0,74.5,54.5,15.2,28.0,36.0

## Center of Measure

In [7]:
possums1[possums1["age"].isnull() == "True"].value_counts()

Series([], Name: count, dtype: int64)

In [8]:
possums.head(5)

,case,site,Pop,sex,age,hdlngth,skullw,totlngth,taill,footlgth,earconch,eye,chest,belly
0,1,1,Vic,m,8.0,94.1,60.4,89.0,36.0,74.5,54.5,15.2,28.0,36.0
1,2,1,Vic,f,6.0,92.5,57.6,91.5,36.5,72.5,51.2,16.0,28.5,33.0
2,3,1,Vic,f,6.0,94.0,60.0,95.5,39.0,75.4,51.9,15.5,30.0,34.0
3,4,1,Vic,f,6.0,93.2,57.1,92.0,38.0,76.1,52.2,15.2,28.0,34.0
4,5,1,Vic,f,2.0,91.5,56.3,85.5,36.0,71.0,53.2,15.1,28.5,33.0

In [9]:
# possums_case_mode = np.mode(possums1['age']
# print(possums_case_mode)

# possums_case_mod = possums1['age'].value_counts()
# possums_case_mod
# print(possums1['earconch'].value_counts().sort_values())
# possums_case_mode = possums1['earconch'].mode()
# possums_case_mode

In [10]:
# 1- Finding mean of Possum

# a - Finding mean of column case
possums_case_mean = np.mean(possums1["case"])
possums_case_median = np.median(possums1["case"])
possums_case_mode = possums1['case'].mode()[0]
print("Data on Case (Observation Number)")
print(f"Mean: {possums_case_mean:.1f}")
print(f"Median: {possums_case_median:.1f}")
print(f"Mode:")
print(f"{possums_case_mode}cm\n")



# b- Finding mean of column Site
print("Data on The site number where the possum was trapped.")
possums_site_mean = np.mean(possums1["site"])
possums_site_median = np.median(possums1["site"])
possums_site_mode = possums1['site'].mode()
print(f"Mean: {possums_site_mean:.1f}")
print(f"Median: {possums_site_median:.1f}")
print(f"Mode:")
print(f"{possums_site_mode}cm\n")



# c- Finding mean of column Age
print("Data on Age")
possums_age_mean = np.nanmean(possums1["age"])
possums_age_median = np.nanmedian(possums1["age"])
possums_age_mode = possums1['age'].mode()
print(f"Mean: {possums_age_mean:.1f}")
print(f"Median: {possums_age_median:.1f}")
print(f"Mode:")
print(f"{possums_age_mode}cm\n")



# d- Finding mean of column Headleanght
print("Data on Head length, in mm.")
possums_hdlngth_mean = np.mean(possums1["hdlngth"])
possums_hdlngth_median = np.median(possums1["hdlngth"])
possums_hdlngth_mode = possums1['hdlngth'].mode()
print(f"Mean: {possums_hdlngth_mean:.1f}mm")
print(f"Median: {possums_hdlngth_median:.1f}mm")
print(f"Mode:")
print(f"{possums_hdlngth_mode}cm\n")


# e- Finding mean of Skullwidth
print("Data on Skull width, in mm.")
possums_skullw_mean = np.mean(possums1["skullw"])
possums_skullw_median = np.median(possums1["skullw"])
possums_skullw_mode = possums1['skullw'].mode()
print(f"Mean: {possums_skullw_mean:.1f}mm")
print(f"Median: {possums_skullw_median:.1f}mm")
print(f"Mode:")
print(f"{possums_skullw_mode}cm\n")



# f- Finding mean of Total length
print("Data on Total length, in cm.")
possums_totlngth_mean = np.mean(possums1["totlngth"])
possums_totlngth_median = np.median(possums1["totlngth"])
possums_totlngth_mode = possums1['totlngth'].mode()
print(f"Mean: {possums_totlngth_mean:.1f}cm")
print(f"Median: {possums_totlngth_median:.1f}cm")
print(f"Mode:")
print(f"{possums_totlngth_mode}cm\n")



# g- Finding mean of Tail length
print("Data on Tail length, in cm.")
possums_taill_mean = np.mean(possums1["taill"])
possums_taill_median = np.median(possums1["taill"])
possums_taill_mode = possums1['taill'].mode()
print(f"Mean: {possums_taill_mean:.1f}cm")
print(f"Median: {possums_taill_median:.1f}cm")
print(f"Mode:")
print(f"{possums_taill_mode}cm\n")


# h- Finding mean of Foot length
print("Data on foot length")
possums_footlgth_mean = np.mean(possums1["footlgth"])
possums_footlgth_median = np.median(possums1["footlgth"])
possums_footlgth_mode = possums1['footlgth'].mode()
print(f"Mean: {possums_footlgth_mean:.1f}cm")
print(f"Median: {possums_footlgth_median:.1f}cm")
print(f"Mode:")
print(f"{possums_footlgth_mode}cm\n")



#i - Finding mean of Ear-conch
print("Data on Ear-conch, in mm.")
possums_earconch_mean = np.mean(possums1["earconch"])
possums_earconch_median = np.median(possums1["earconch"])
possums_earconch_mode = possums1['earconch'].mode()
print(f"Mean: {possums_earconch_mean:.1f}mm")
print(f"Median: {possums_earconch_median:.1f}mm")
print(f"Mode:")
print(f"{possums_earconch_mode}cm\n")


#j - Finding mean of eye distance from medial canthus to lateral canthus of right eye
print("Data on Eye Distance from Medial Canthus, in mm.")
possums_eye_mean = np.mean(possums1["eye"])
possums_eye_median = np.median(possums1["eye"])
possums_eye_mode = possums1['eye'].mode()
print(f"Mean: {possums_eye_mean:.1f}mm")
print(f"Median: {possums_eye_median:.1f}mm")
print(f"Mode:")
print(f"{possums_eye_mode}cm\n")


#k - Finding mean of chest girth (in cm)
print("Data on Chest girth, in cm.")
possums_chest_mean = np.mean(possums1["chest"])
possums_chest_median = np.median(possums1["chest"])
possums_chest_mode = possums1['chest'].mode()
print(f"Mean: {possums_chest_mean:.1f}cm")
print(f"Median: {possums_chest_median:.1f}cm")
print(f"Mode:")
print(f"{possums_chest_mode}cm\n")


#l - Finding mean of belly girth (in cm)
print("Data on belly girth, in cm.")
possums_belly_mean = np.mean(possums1["belly"])
possums_belly_median = np.median(possums1["belly"])
possums_belly_mode = possums1['belly'].mode()
print(f"Mean: {possums_belly_mean:.1f}cm")
print(f"Median: {possums_belly_mean:.1f}cm")
print(f"Mode:")
print(f"{possums_belly_mode}cm\n")




# possums_mean = np.mean(possums1.select_dtypes(include=[np.number]))
# print("The mean of possum is:", possums_mean)

Data on Case (Observation Number)
Mean: 52.5
Median: 52.5
Mode:
1cm

Data on The site number where the possum was trapped.
Mean: 3.6
Median: 3.0
Mode:
0    1
Name: site, dtype: int64cm

Data on Age
Mean: 3.8
Median: 3.0
Mode:
0    3.0
Name: age, dtype: float64cm

Data on Head length, in mm.
Mean: 92.6mm
Median: 92.8mm
Mode:
0    93.3
Name: hdlngth, dtype: float64cm

Data on Skull width, in mm.
Mean: 56.9mm
Median: 56.3mm
Mode:
0    57.6
Name: skullw, dtype: float64cm

Data on Total length, in cm.
Mean: 87.1cm
Median: 88.0cm
Mode:
0    89.0
Name: totlngth, dtype: float64cm

Data on Tail length, in cm.
Mean: 37.0cm
Median: 37.0cm
Mode:
0    38.0
Name: taill, dtype: float64cm

Data on foot length
Mean: 68.5cm
Median: nancm
Mode:
0    73.2
Name: footlgth, dtype: float64cm

Data on Ear-conch, in mm.
Mean: 48.1mm
Median: 46.8mm
Mode:
0    44.9
1    46.0
2    46.8
3    52.0
Name: earconch, dtype: float64cm

Data on Eye Distance from Medial Canthus, in mm.
Mean: 15.0mm
Median: 14.9mm
Mode:
0    14.4
1    14.5
Name: eye, dtype: float64cm

Data on Chest girth, in cm.
Mean: 27.0cm
Median: 27.0cm
Mode:
0    28.0
Name: chest, dtype: float64cm

Data on belly girth, in cm.
Mean: 32.6cm
Median: 32.6cm
Mode:
0    32.0
1    33.0
Name: belly, dtype: float64cm

Measure of Spread

In [11]:
possums1.head(1)

,case,site,Pop,sex,age,hdlngth,skullw,totlngth,taill,footlgth,earconch,eye,chest,belly
0,1,1,Vic,m,8.0,94.1,60.4,89.0,36.0,74.5,54.5,15.2,28.0,36.0

In [12]:
# Finding Range

# a - Finding mean of column case
print("Data on Case:")
possums_case_range = possums1['case'].max() - possums1['case'].min()
possums_case_var = possums1["case"].var()
possums_case_std = possums1['belly'].std()
print(f"Range: {possums_case_range:.1f}")
print(f"Variance: {possums_case_var:.1f}")
print(f"Standard Deviation: {possums_case_std:.1f}\n")


# c- Finding mean of column Age
print("Data on Site:")
possums_site_range = possums1['site'].max() - possums1['site'].min()
possums_site_var = possums1["site"].var()
possums_site_std = possums1['site'].std()
print(f"Range: {possums_site_range:.1f}")
print(f"Variance: {possums_site_var:.1f}")
print(f"Standard Deviation: {possums_site_std:.1f}\n")

# c- Finding mean of column Age
print("Data on Age:")
possums_age_range = possums1['age'].max() - possums1['age'].min()
possums_age_var = possums1["age"].var()
possums_age_std = possums1['age'].std()
print(f"Range: {possums_age_range:.1f}")
print(f"Variance: {possums_age_var:.1f}")
print(f"Standard Deviation: {possums_age_std:.1f}\n")

print("Data on Age:")
possums_hdlngth_range = possums1['hdlngth'].max() - possums1['hdlngth'].min()
possums_hdlngth_var = possums1["hdlngth"].var()
possums_hdlngth_std = possums1['hdlngth'].std()
print(f"Range: {possums_hdlngth_range:.1f}")
print(f"Variance: {possums_hdlngth_var:.1f}")
print(f"Standard Deviation: {possums_hdlngth_std:.1f}\n")


print("<===Data on Skull Width===>")
possums_skullw_range = possums1['skullw'].max() - possums1['skullw'].min()
possums_skullw_var = possums1["skullw"].var()
possums_skullw_std = possums1['skullw'].std()
print(f"Range: {possums_skullw_range:.1f}")
print(f"Variance: {possums_skullw_var:.1f}")
print(f"Standard Deviation: {possums_skullw_std:.1f}\n")


print("<===Data on Total Length===>")
possums_totlngth_range = possums1['totlngth'].max() - possums1['totlngth'].min()
possums_totlngth_var = possums1["totlngth"].var()
possums_totlngth_std = possums1['totlngth'].std()
print(f"Range: {possums_totlngth_range:.1f}")
print(f"Variance: {possums_totlngth_var:.1f}")
print(f"Standard Deviation: {possums_totlngth_std:.1f}\n")


print("<===Data on Tail Length===>")
possums_taill_range = possums1['taill'].max() - possums1['taill'].min()
possums_taill_var = possums1["taill"].var()
possums_taill_std = possums1['taill'].std()
print(f"Range: {possums_taill_range:.1f}")
print(f"Variance: {possums_taill_var:.1f}")
print(f"Standard Deviation: {possums_taill_std:.1f}\n")


print("<===Data on Foot Length===>")
possums_footlgth_range = possums1['footlgth'].max() - possums1['footlgth'].min()
possums_footlgth_var = possums1["footlgth"].var()
possums_footlgth_std = possums1['footlgth'].std()
print(f"Range: {possums_footlgth_range:.1f}")
print(f"Variance: {possums_footlgth_var:.1f}")
print(f"Standard Deviation: {possums_footlgth_std:.1f}\n")


print("<===Data on Ear-conch Length===>")
possums_earconch_range = possums1['earconch'].max() - possums1['earconch'].min()
possums_earconch_var = possums1["earconch"].var()
possums_earconch_std = possums1['earconch'].std()
print(f"Range: {possums_earconch_range:.1f}")
print(f"Variance: {possums_earconch_var:.1f}")
print(f"Standard Deviation: {possums_earconch_std:.1f}\n")



print("<===Data on Eye Distance from Medial Cathus===>")
possums_eye_range = possums1['eye'].max() - possums1['eye'].min()
possums_eye_var = possums1["eye"].var()
possums_eye_std = possums1['eye'].std()
print(f"Range: {possums_eye_range:.1f}")
print(f"Variance: {possums_eye_var:.1f}")
print(f"Standard Deviation: {possums_eye_std:.1f}\n")


print("<===Data on Chest ===>")
possums_chest_range = possums1['chest'].max() - possums1['chest'].min()
possums_chest_var = possums1["chest"].var()
possums_chest_std = possums1['chest'].std()
print(f"Range: {possums_chest_range:.1f}")
print(f"Variance: {possums_chest_var:.1f}")
print(f"Standard Deviation: {possums_chest_std:.1f}\n")


print("<===Data on Chest ===>")
possums_belly_range = possums1['belly'].max() - possums1['belly'].min()
possums_belly_var = possums1["belly"].var()
possums_belly_std = possums1['belly'].std()
print(f"Range: {possums_belly_range:.1f}")
print(f"Variance: {possums_belly_var:.1f}")
print(f"Standard Deviation: {possums_belly_std:.1f}\n")

Data on Case:
Range: 103.0
Variance: 910.0
Standard Deviation: 2.8

Data on Site:
Range: 6.0
Variance: 5.5
Standard Deviation: 2.3

Data on Age:
Range: 8.0
Variance: 3.6
Standard Deviation: 1.9

Data on Age:
Range: 20.6
Variance: 12.8
Standard Deviation: 3.6

<===Data on Skull Width===>
Range: 18.6
Variance: 9.7
Standard Deviation: 3.1

<===Data on Total Length===>
Range: 21.5
Variance: 18.6
Standard Deviation: 4.3

<===Data on Tail Length===>
Range: 11.0
Variance: 3.8
Standard Deviation: 2.0

<===Data on Foot Length===>
Range: 17.6
Variance: 19.3
Standard Deviation: 4.4

<===Data on Ear-conch Length===>
Range: 15.9
Variance: 16.9
Standard Deviation: 4.1

<===Data on Eye Distance from Medial Cathus===>
Range: 5.0
Variance: 1.1
Standard Deviation: 1.1

<===Data on Chest ===>
Range: 10.0
Variance: 4.2
Standard Deviation: 2.0

<===Data on Chest ===>
Range: 15.0
Variance: 7.6
Standard Deviation: 2.8

In [13]:
possums.head(1)

,case,site,Pop,sex,age,hdlngth,skullw,totlngth,taill,footlgth,earconch,eye,chest,belly
0,1,1,Vic,m,8.0,94.1,60.4,89.0,36.0,74.5,54.5,15.2,28.0,36.0

In [14]:
possums_cols = ["sex", "age", ]